modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="cavarli"
version="1.0.0"
displayName="cavarli904"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="TrainingGR17, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.cavarli]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.cavarli]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration